export const meta = {
  name: 'concept-link-revalidate-run3',
  description: 'Faithful concept_linker pick+verify over ALL 274 companies (run 3/3, stability)',
  phases: [{ title: 'Match', detail: 'one agent per company runs the exact pick+verify' }],
}
const tickers = ["A", "AA", "AAL", "AAP", "AAPL", "ABBV", "ABM", "ABNB", "ABT", "ACAD", "ACCD", "ACHC", "ACI", "ACM", "ACMR", "ACN", "ADBE", "ADC", "ADI", "ADM", "ADNT", "ADSK", "AEE", "AEIS", "AEP", "AES", "AFL", "AFRM", "AGIO", "AGNC", "AHCO", "AI", "AIG", "AIR", "AJG", "AKAM", "ALB", "ALEX", "ALGN", "ALGT", "ALK", "ALKS", "ALL", "ALLE", "ALNY", "ALSN", "ALT", "ALV", "AMAT", "AMBA", "AMC", "AMCX", "AMD", "AME", "AMED", "AMG", "AMGN", "AMH", "AMP", "AMRC", "AMRX", "AMT", "AMTX", "AMZN", "ANET", "ANF", "ANSS", "APA", "APD", "APH", "APLS", "APO", "APPN", "AR", "ARDX", "ARES", "ARMK", "ARRY", "ARVN", "ARWR", "ASAN", "ASH", "ASO", "ATEC", "ATO", "ATRC", "AUPH", "AVAV", "AVGO", "AVXL", "AVY", "AWI", "AWK", "AXL", "AXSM", "AXTA", "AYI", "AZEK", "AZO", "BA", "BAH", "BAND", "BAX", "BBIO", "BBY", "BC", "BCRX", "BDX", "BE", "BEAM", "BECN", "BEN", "BERY", "BFAM", "BG", "BIGC", "BILL", "BJ", "BK", "BL", "BLD", "BLDR", "BLK", "BLMN", "BMBL", "BMY", "BOOT", "BOX", "BPMC", "BR", "BRBR", "BRX", "BRZE", "BSX", "BSY", "BURL", "BWA", "BX", "BXP", "CACI", "CAG", "CAH", "CAKE", "CALX", "CARG", "CASY", "CAT", "CBOE", "CBRE", "CBRL", "CC", "CCK", "CCL", "CDLX", "CDNA", "CDW", "CE", "CEG", "CF", "CFLT", "CG", "CGNX", "CHGG", "CHH", "CHRW", "CHTR", "CHWY", "CI", "CIEN", "CL", "CLF", "CLSK", "CLX", "CMC", "CMCSA", "CMG", "CNK", "CNM", "CNS", "COIN", "COO", "COST", "COTY", "COUR", "CP", "CPB", "CPRT", "CPRX", "CPT", "CRI", "CRM", "CROX", "CRSP", "CRWD", "CSCO", "CSTL", "CTAS", "CTSH", "CTVA", "CVNA", "CVS", "CWH", "CWK", "CXM", "CYRX", "CYTK", "D", "DAL", "DAN", "DAR", "DASH", "DBX", "DDOG", "DE", "DECK", "DELL", "DGX", "DH", "DHI", "DHR", "DIS", "DK", "DKS", "DLR", "DLTR", "DNB", "DNUT", "DOCN", "DOCS", "DOCU", "DOMO", "DOV", "DOW", "DRI", "DT", "DTE", "DUK", "DUOL", "DV", "DVN", "DXC", "DXCM", "DY", "EAT", "EBAY", "ECL", "ED", "EDIT", "EEFT", "EFX", "EIX", "EL", "ELAN", "ELF", "EMN", "EMR", "ENPH", "ENR", "ENTA", "EOG", "EOLS", "EPAM", "EPC", "EPD", "EQT", "ESS", "ESTC", "ETSY", "EVER", "EXAS", "EXEL", "EXPD", "EXPE", "EYE"]
const PROMPT = (t) => `You are the LLM inside an XBRL concept-matcher. Read /tmp/claude-1000/-home-faisal-EventMarketDB/1fc7fcb8-680c-48d0-a64c-ac3f73b686ef/scratchpad/clrv/probe/${t}.json (fields: menu=[{qname,label,usage}] = the ONLY allowed answers; metrics=[slugs]).\nFor EACH metric, run TWO independent steps, treating every metric in isolation:\nSTEP 1 PICK: Pick the ONE menu qname that IS exactly this metric (the same accounting line a filer tags), or null. SAME metric only — a related-but-different line is NOT a match (cost-of-revenue\u2260revenue; income-tax\u2260net-income; a subtotal\u2260the total; basic\u2260diluted). Two equal candidates \u2192 higher usage.\nSTEP 2 VERIFY (only if PICK is non-null): STRICT auditor, default to refuted when unsure (a wrong link is the cardinal sin). Refute if the concept is a related-but-different line, a different value (GAAP vs non-GAAP, gross vs net, subtotal vs total), the wrong statement, or a dimension instead of the consolidated line. Output real=true only if it survives.\nWrite /tmp/claude-1000/-home-faisal-EventMarketDB/1fc7fcb8-680c-48d0-a64c-ac3f73b686ef/scratchpad/clrv/run3/${t}.json = a JSON array [{"slug","qname": "us-gaap:..." or null,"real": true|false}] covering EVERY metric exactly once (real=false when qname is null). Return only "${t}: done".`
phase('Match')
await parallel(tickers.map(t => () => agent(PROMPT(t), { label: `r3:${t}`, phase: 'Match' })))
return { run: 3, companies: tickers.length, out: '/tmp/claude-1000/-home-faisal-EventMarketDB/1fc7fcb8-680c-48d0-a64c-ac3f73b686ef/scratchpad/clrv/run3' }
