apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"neo4j","namespace":"neo4j"},"spec":{"clusterIP":"None","ports":[{"name":"bolt","port":7687,"targetPort":7687},{"name":"http","port":7474,"targetPort":7474}],"selector":{"app":"neo4j"}}}
    creationTimestamp: "2025-07-06T05:36:10Z"
    name: neo4j
    namespace: neo4j
    resourceVersion: "5647051"
    uid: dfca0922-0190-4b30-af49-ca0c2a1e3d96
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: http
      port: 7474
      protocol: TCP
      targetPort: 7474
    selector:
      app: neo4j
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"neo4j-bolt","namespace":"neo4j"},"spec":{"ports":[{"name":"bolt","nodePort":30687,"port":7687,"targetPort":7687}],"selector":{"app":"neo4j"},"type":"NodePort"}}
    creationTimestamp: "2025-07-06T05:36:10Z"
    name: neo4j-bolt
    namespace: neo4j
    resourceVersion: "5647068"
    uid: 6014fb3e-168f-41bd-a518-8da2d34e035d
  spec:
    clusterIP: 10.102.222.120
    clusterIPs:
    - 10.102.222.120
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: bolt
      nodePort: 30687
      port: 7687
      protocol: TCP
      targetPort: 7687
    selector:
      app: neo4j
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"neo4j-http","namespace":"neo4j"},"spec":{"ports":[{"name":"http","nodePort":30474,"port":7474,"targetPort":7474}],"selector":{"app":"neo4j"},"type":"NodePort"}}
    creationTimestamp: "2025-07-06T05:36:10Z"
    name: neo4j-http
    namespace: neo4j
    resourceVersion: "5647079"
    uid: fbdb3bcb-0572-4b65-9ada-a35f6ac52f2b
  spec:
    clusterIP: 10.107.215.244
    clusterIPs:
    - 10.107.215.244
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30474
      port: 7474
      protocol: TCP
      targetPort: 7474
    selector:
      app: neo4j
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
