ten_k_sections = {
    '1': 'Business',
    '1A': 'RiskFactors',
    '1B': 'UnresolvedStaffComments',
    '1C': 'Cybersecurity',
    '2': 'Properties',
    '3': 'LegalProceedings',
    '4': 'MineSafetyDisclosures',
    '5': 'MarketforRegistrant’sCommonEquity,RelatedStockholderMattersandIssuerPurchasesofEquitySecurities',
    '6': 'SelectedFinancialData(priortoFebruary2021)',
    '7': 'Management’sDiscussionandAnalysisofFinancialConditionandResultsofOperations',
    '7A': 'QuantitativeandQualitativeDisclosuresaboutMarketRisk',
    '8': 'FinancialStatementsandSupplementaryData',
    '9': 'ChangesinandDisagreementswithAccountantsonAccountingandFinancialDisclosure',
    '9A': 'ControlsandProcedures',
    '9B': 'OtherInformation',
    '10': 'Directors,ExecutiveOfficersandCorporateGovernance',
    '11': 'ExecutiveCompensation',
    '12': 'SecurityOwnershipofCertainBeneficialOwnersandManagementandRelatedStockholderMatters',
    '13': 'CertainRelationshipsandRelatedTransactions,andDirectorIndependence',
    '14': 'PrincipalAccountantFeesandServices',
    '15': 'ExhibitsandFinancialStatementSchedules'
}


ten_q_sections = {
    'Part1_1': 'FinancialStatements',
    'Part1_2': 'Management’sDiscussionandAnalysisofFinancialConditionandResultsofOperations',
    'Part1_3': 'QuantitativeandQualitativeDisclosuresAboutMarketRisk',
    'Part1_4': 'ControlsandProcedures',
    'Part2_1': 'LegalProceedings',
    'Part2_1A': 'RiskFactors',
    'Part2_2': 'UnregisteredSalesofEquitySecuritiesandUseofProceeds',
    'Part2_3': 'DefaultsUponSeniorSecurities',
    'Part2_4': 'MineSafetyDisclosures',
    'Part2_5': 'OtherInformation',
    'Part2_6': 'Exhibits'
}

eight_k_sections = {
    '1.01': 'EntryintoaMaterialDefinitiveAgreement',
    '1.02': 'TerminationofaMaterialDefinitiveAgreement',
    '1.03': 'BankruptcyorReceivership',
    '1.04': 'MineSafety-ReportingofShutdownsandPatternsofViolations',
    '1.05': 'MaterialCybersecurityIncidents(introducedin2023)',
    '2.01': 'CompletionofAcquisitionorDispositionofAssets',
    '2.02': 'ResultsofOperationsandFinancialCondition',
    '2.03': 'CreationofaDirectFinancialObligationoranObligationunderanOff-BalanceSheetArrangementofaRegistrant',
    '2.04': 'TriggeringEventsThatAccelerateorIncreaseaDirectFinancialObligationoranObligationunderanOff-BalanceSheetArrangement',
    '2.05': 'CostAssociatedwithExitorDisposalActivities',
    '2.06': 'MaterialImpairments',
    '3.01': 'NoticeofDelistingorFailuretoSatisfyaContinuedListingRuleorStandard;TransferofListing',
    '3.02': 'UnregisteredSalesofEquitySecurities',
    '3.03': 'MaterialModificationstoRightsofSecurityHolders',
    '4.01': 'ChangesinRegistrant’sCertifyingAccountant',
    '4.02': 'Non-RelianceonPreviouslyIssuedFinancialStatementsoraRelatedAuditReportorCompletedInterimReview',
    '5.01': 'ChangesinControlofRegistrant',
    '5.02': 'DepartureofDirectorsorCertainOfficers;ElectionofDirectors;AppointmentofCertainOfficers:CompensatoryArrangementsofCertainOfficers',
    '5.03': 'AmendmentstoArticlesofIncorporationorBylaws;ChangeinFiscalYear',
    '5.04': 'TemporarySuspensionofTradingUnderRegistrant’sEmployeeBenefitPlans',
    '5.05': 'AmendmentstotheRegistrant’sCodeofEthics,orWaiverofaProvisionoftheCodeofEthics',
    '5.06': 'ChangeinShellCompanyStatus',
    '5.07': 'SubmissionofMatterstoaVoteofSecurityHolders',
    '5.08': 'ShareholderNominationsPursuanttoExchangeActRule14a-11',
    '6.01': 'ABSInformationalandComputationalMaterial',
    '6.02': 'ChangeofServicerorTrustee',
    '6.03': 'ChangeinCreditEnhancementorOtherExternalSupport',
    '6.04': 'FailuretoMakeaRequiredDistribution',
    '6.05': 'SecuritiesActUpdatingDisclosure',
    '6.06': 'StaticPool',
    '6.10': 'AlternativeFilingsofAsset-BackedIssuers',
    '7.01': 'RegulationFDDisclosure',
    '8.01': 'OtherEvents',
    '9.01': 'FinancialStatementsandExhibits',
    'Signature': 'Signature'
}
