---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xbrl-worker-heavy-scaler
  namespace: processing
spec:
  scaleTargetRef:
    name: xbrl-worker-heavy
  minReplicaCount: 0              # Scale to zero when idle
  maxReplicaCount: 5              # Max 5 heavy workers (40GB RAM total)
  cooldownPeriod: 300             # 5 min cooldown for heavy tasks
  triggers:
  - type: redis
    metadata:
      address: redis.infrastructure.svc.cluster.local:6379
      listName: reports:queues:xbrl:heavy
      listLength: "2"             # 1 pod per 2 heavy reports (they take long)
      activationListLength: "1"   # Wake from 0 when queue has items
      databaseIndex: "0"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xbrl-worker-medium-scaler
  namespace: processing
spec:
  scaleTargetRef:
    name: xbrl-worker-medium
  minReplicaCount: 0              # Scale to zero when idle
  maxReplicaCount: 3              # Max 3 medium workers (12GB RAM total)
  cooldownPeriod: 180             # 3 min cooldown
  triggers:
  - type: redis
    metadata:
      address: redis.infrastructure.svc.cluster.local:6379
      listName: reports:queues:xbrl:medium
      listLength: "5"             # 1 pod per 5 medium reports
      activationListLength: "1"
      databaseIndex: "0"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: xbrl-worker-light-scaler
  namespace: processing
spec:
  scaleTargetRef:
    name: xbrl-worker-light
  minReplicaCount: 0              # Scale to zero when idle
  maxReplicaCount: 6              # Max 6 light workers (12GB RAM total)
  cooldownPeriod: 120             # 2 min cooldown for quick tasks
  triggers:
  - type: redis
    metadata:
      address: redis.infrastructure.svc.cluster.local:6379
      listName: reports:queues:xbrl:light
      listLength: "20"            # 1 pod per 20 light reports (they're fast)
      activationListLength: "1"
      databaseIndex: "0"