apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"redis-pvc","namespace":"infrastructure"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"40Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: minisforum2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-07-06T06:06:02Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: redis-pvc
    namespace: infrastructure
    resourceVersion: "5652573"
    uid: d8ba547a-4892-4d75-aa5a-f5b5b3483187
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 40Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-d8ba547a-4892-4d75-aa5a-f5b5b3483187
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 40Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
