apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: nats
      meta.helm.sh/release-namespace: infrastructure
    creationTimestamp: "2025-07-06T05:35:38Z"
    labels:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nats
      app.kubernetes.io/version: 2.11.6
      helm.sh/chart: nats-1.3.9
    name: nats
    namespace: infrastructure
    resourceVersion: "5646924"
    uid: 820bb37f-859b-45f6-b993-6effbafcb35a
  spec:
    clusterIP: 10.107.38.43
    clusterIPs:
    - 10.107.38.43
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      protocol: TCP
      targetPort: nats
    selector:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: nats
      meta.helm.sh/release-namespace: infrastructure
    creationTimestamp: "2025-07-06T05:35:38Z"
    labels:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: nats
      app.kubernetes.io/version: 2.11.6
      helm.sh/chart: nats-1.3.9
    name: nats-headless
    namespace: infrastructure
    resourceVersion: "5646920"
    uid: 0fc50f18-7916-4c2e-95ec-dfaf4cd12f47
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      protocol: TCP
      targetPort: nats
    - appProtocol: http
      name: monitor
      port: 8222
      protocol: TCP
      targetPort: monitor
    publishNotReadyAddresses: true
    selector:
      app.kubernetes.io/component: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis","namespace":"infrastructure"},"spec":{"ports":[{"nodePort":31379,"port":6379,"targetPort":6379}],"selector":{"app":"redis"},"type":"NodePort"}}
    creationTimestamp: "2025-07-06T06:04:59Z"
    name: redis
    namespace: infrastructure
    resourceVersion: "5652383"
    uid: 1fdce587-74a4-46fd-b9e0-08c46ece18cd
  spec:
    clusterIP: 10.105.197.130
    clusterIPs:
    - 10.105.197.130
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31379
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
