apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: minisforum2
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-07-06T05:36:45Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
      operator.prometheus.io/shard: "0"
      prometheus: prometheus-kube-prometheus-prometheus
    name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
    namespace: monitoring
    resourceVersion: "5647590"
    uid: 51f73d5d-9be3-4e87-91fd-97c3da595674
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-51f73d5d-9be3-4e87-91fd-97c3da595674
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 100Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: minisforum
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-07-06T05:37:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: loki
      release: loki
    name: storage-loki-0
    namespace: monitoring
    resourceVersion: "5647784"
    uid: 804a1738-9246-42da-81f5-fe2f5124d49f
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-804a1738-9246-42da-81f5-fe2f5124d49f
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
