apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mcp-neo4j-cypher"},"name":"mcp-neo4j-cypher","namespace":"mcp-services"},"spec":{"ports":[{"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"mcp-neo4j-cypher"},"type":"ClusterIP"}}
    labels:
      app: mcp-neo4j-cypher
    name: mcp-neo4j-cypher
    namespace: mcp-services
  spec:
    - 10.108.7.25
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: mcp-neo4j-cypher
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mcp-neo4j-memory"},"name":"mcp-neo4j-memory","namespace":"mcp-services"},"spec":{"ports":[{"port":3001,"protocol":"TCP","targetPort":3001}],"selector":{"app":"mcp-neo4j-memory"},"type":"ClusterIP"}}
    labels:
      app: mcp-neo4j-memory
    name: mcp-neo4j-memory
    namespace: mcp-services
  spec:
    - 10.98.141.17
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
    selector:
      app: mcp-neo4j-memory
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
