apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      meta.helm.sh/release-name: keda
      meta.helm.sh/release-namespace: keda
    creationTimestamp: "2025-07-04T10:27:05Z"
    generation: 2
    labels:
      app: keda-admission-webhooks
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: keda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keda-admission-webhooks
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.17.2
      helm.sh/chart: keda-2.17.2
      name: keda-admission-webhooks
    name: keda-admission-webhooks
    namespace: keda
    resourceVersion: "5787626"
    uid: ec22d4bf-4562-4059-96e3-9bf3b2478c03
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: keda-admission-webhooks
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-07-04T20:02:00-04:00"
        creationTimestamp: null
        labels:
          app: keda-admission-webhooks
          app.kubernetes.io/component: operator
          app.kubernetes.io/instance: keda
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: keda-admission-webhooks
          app.kubernetes.io/part-of: keda-operator
          app.kubernetes.io/version: 2.17.2
          helm.sh/chart: keda-2.17.2
          name: keda-admission-webhooks
      spec:
        automountServiceAccountToken: true
        containers:
        - args:
          - --zap-log-level=info
          - --zap-encoder=console
          - --zap-time-encoding=rfc3339
          - --cert-dir=/certs
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=:8080
          command:
          - /keda-admission-webhooks
          env:
          - name: WATCH_NAMESPACE
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: ghcr.io/kedacore/keda-admission-webhooks:2.17.2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: keda-admission-webhooks
          ports:
          - containerPort: 9443
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /certs
            name: certificates
            readOnly: true
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: keda-webhook
        serviceAccountName: keda-webhook
        terminationGracePeriodSeconds: 30
        volumes:
        - name: certificates
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-07-04T10:27:05Z"
      lastUpdateTime: "2025-07-05T00:02:24Z"
      message: ReplicaSet "keda-admission-webhooks-67747f694c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-07-06T23:07:43Z"
      lastUpdateTime: "2025-07-06T23:07:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      meta.helm.sh/release-name: keda
      meta.helm.sh/release-namespace: keda
    creationTimestamp: "2025-07-04T10:27:05Z"
    generation: 2
    labels:
      app: keda-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: keda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keda-operator
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.17.2
      helm.sh/chart: keda-2.17.2
      name: keda-operator
    name: keda-operator
    namespace: keda
    resourceVersion: "5982135"
    uid: e0046668-90ed-42fe-9b4d-83bdd5ea04c4
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: keda-operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-07-04T20:02:00-04:00"
        creationTimestamp: null
        labels:
          app: keda-operator
          app.kubernetes.io/component: operator
          app.kubernetes.io/instance: keda
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: keda-operator
          app.kubernetes.io/part-of: keda-operator
          app.kubernetes.io/version: 2.17.2
          helm.sh/chart: keda-2.17.2
          name: keda-operator
      spec:
        automountServiceAccountToken: true
        containers:
        - args:
          - --leader-elect
          - --disable-compression=true
          - --zap-log-level=info
          - --zap-encoder=console
          - --zap-time-encoding=rfc3339
          - --enable-webhook-patching=true
          - --cert-dir=/certs
          - --enable-cert-rotation=true
          - --cert-secret-name=kedaorg-certs
          - --operator-service-name=keda-operator
          - --metrics-server-service-name=keda-operator-metrics-apiserver
          - --webhooks-service-name=keda-admission-webhooks
          - --k8s-cluster-name=kubernetes-default
          - --k8s-cluster-domain=cluster.local
          - --enable-prometheus-metrics=false
          command:
          - /keda
          env:
          - name: WATCH_NAMESPACE
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: keda-operator
          - name: KEDA_HTTP_DEFAULT_TIMEOUT
            value: "3000"
          - name: KEDA_HTTP_MIN_TLS_VERSION
            value: TLS12
          image: ghcr.io/kedacore/keda:2.17.2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: keda-operator
          ports:
          - containerPort: 9666
            name: metricsservice
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /certs
            name: certificates
            readOnly: true
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: keda-operator
        serviceAccountName: keda-operator
        terminationGracePeriodSeconds: 30
        volumes:
        - name: certificates
          secret:
            defaultMode: 420
            optional: true
            secretName: kedaorg-certs
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-07-04T10:27:05Z"
      lastUpdateTime: "2025-07-05T00:02:30Z"
      message: ReplicaSet "keda-operator-646c97b599" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-07-07T21:49:29Z"
      lastUpdateTime: "2025-07-07T21:49:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      meta.helm.sh/release-name: keda
      meta.helm.sh/release-namespace: keda
    creationTimestamp: "2025-07-04T10:27:05Z"
    generation: 2
    labels:
      app: keda-operator-metrics-apiserver
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: keda
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: keda-operator-metrics-apiserver
      app.kubernetes.io/part-of: keda-operator
      app.kubernetes.io/version: 2.17.2
      helm.sh/chart: keda-2.17.2
    name: keda-operator-metrics-apiserver
    namespace: keda
    resourceVersion: "5404368"
    uid: bfe0cfd2-140d-4948-8bac-dd8538dfec3a
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: keda-operator-metrics-apiserver
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2025-07-04T20:02:00-04:00"
        creationTimestamp: null
        labels:
          app: keda-operator-metrics-apiserver
          app.kubernetes.io/component: operator
          app.kubernetes.io/instance: keda
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: keda-operator-metrics-apiserver
          app.kubernetes.io/part-of: keda-operator
          app.kubernetes.io/version: 2.17.2
          helm.sh/chart: keda-2.17.2
      spec:
        automountServiceAccountToken: true
        containers:
        - args:
          - --port=8080
          - --secure-port=6443
          - --logtostderr=true
          - --stderrthreshold=ERROR
          - --disable-compression=true
          - --metrics-service-address=keda-operator.keda.svc.cluster.local:9666
          - --client-ca-file=/certs/ca.crt
          - --tls-cert-file=/certs/tls.crt
          - --tls-private-key-file=/certs/tls.key
          - --cert-dir=/certs
          - --v=0
          command:
          - /keda-adapter
          env:
          - name: WATCH_NAMESPACE
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: KEDA_HTTP_DEFAULT_TIMEOUT
            value: "3000"
          - name: KEDA_HTTP_MIN_TLS_VERSION
            value: TLS12
          image: ghcr.io/kedacore/keda-metrics-apiserver:2.17.2
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: keda-operator-metrics-apiserver
          ports:
          - containerPort: 6443
            name: https
            protocol: TCP
          - containerPort: 8080
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 6443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /certs
            name: certificates
            readOnly: true
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
        serviceAccount: keda-metrics-server
        serviceAccountName: keda-metrics-server
        terminationGracePeriodSeconds: 30
        volumes:
        - name: certificates
          secret:
            defaultMode: 420
            secretName: kedaorg-certs
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-07-04T10:27:21Z"
      lastUpdateTime: "2025-07-04T10:27:21Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-07-04T10:27:05Z"
      lastUpdateTime: "2025-07-05T00:02:09Z"
      message: ReplicaSet "keda-operator-metrics-apiserver-668d6787f9" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
