apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mcp-neo4j-cypher"},"name":"mcp-neo4j-cypher","namespace":"mcp-services"},"spec":{"ports":[{"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"mcp-neo4j-cypher"},"type":"ClusterIP"}}
    creationTimestamp: "2025-07-06T05:42:53Z"
    labels:
      app: mcp-neo4j-cypher
    name: mcp-neo4j-cypher
    namespace: mcp-services
    resourceVersion: "5648549"
    uid: a10b9c97-2031-4bb8-bda1-0f2834875107
  spec:
    clusterIP: 10.108.7.25
    clusterIPs:
    - 10.108.7.25
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: mcp-neo4j-cypher
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mcp-neo4j-memory"},"name":"mcp-neo4j-memory","namespace":"mcp-services"},"spec":{"ports":[{"port":3001,"protocol":"TCP","targetPort":3001}],"selector":{"app":"mcp-neo4j-memory"},"type":"ClusterIP"}}
    creationTimestamp: "2025-07-06T05:42:58Z"
    labels:
      app: mcp-neo4j-memory
    name: mcp-neo4j-memory
    namespace: mcp-services
    resourceVersion: "5648578"
    uid: a7f4c4e3-097b-4c1c-a43d-5e5dea5f69c6
  spec:
    clusterIP: 10.98.141.17
    clusterIPs:
    - 10.98.141.17
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
    selector:
      app: mcp-neo4j-memory
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
