#!/bin/bash
# ONE sequential evidence run for the A3 durable checkpoint (Codex SEQ 1561 item 4).
# No transcript replay and no open census. The attempt evidence is accounted from the
# exact surviving bytes, the receipts are reconstructed, the real finalization and the
# real entry point run inside the package-backed projection, then every mutation, the
# audit, one freeze, the full suite and the manifest verification. The previous round started the
# audit and the suite seven seconds apart, so they overlapped: concurrent tests are not
# proof of isolated state. Each step here waits for the one before it, and every step
# is stamped so the ORDER is part of the evidence, not a claim about it.
set -u
P=/home/faisal/.core827_backups/recovery_1531/regen_1541
# -u: WITHOUT IT A KILLED STEP LEAVES NO OUTPUT AT ALL. Buffered stdout dies with
# the process, which is exactly what made an earlier silent death hard to trace.
PY="/home/faisal/EventMarketDB/venv/bin/python -u"
export PYTHONDONTWRITEBYTECODE=1
LOG=$P/logs/ordered_1558.txt
: > "$LOG"
step() {
  echo "== $(date '+%F %T.%3N') BEGIN $1" >> "$LOG"
  shift
  "$@" >> "$LOG" 2>&1
  # CAPTURE rc FIRST. Writing `rc=$?` inside an echo whose argument also contains
  # $(date ...) reports the DATE's status: the command substitution runs before the
  # expansion of $?, so every step logged rc=0 - including one the kernel killed.
  rc=$?
  echo "== $(date '+%F %T.%3N') END   rc=$rc" >> "$LOG"
  if [ "$rc" -ne 0 ]; then
    echo "!! STEP FAILED rc=$rc - the ordered run stops here" >> "$LOG"
    exit "$rc"
  fi
}
cd "$P" || exit 1

# PROVE THE RUN IS FROZEN. The previous chain began at 16:41:47 and I then edited a
# proof at 16:48:55 and added a test at 16:55:32, so its early steps did not cover the
# sources its later steps used. Every source and test is hashed HERE and re-hashed at
# the end; any difference voids the run rather than being found by a reviewer.
# FRESH, ISOLATED, EMPTY CACHE and no bytecode before anything is frozen or run: a
# cache built against other inputs must never be served (Codex SEQ 1559 item 2).
rm -rf "$P/sibling_cache" && mkdir -p "$P/sibling_cache"
# the resume run's HOME is the package's own `home/`: empty before the run, so any file
# a process writes there shows in the decision-input diff rather than surviving unseen
rm -rf "$P/home" && mkdir -p "$P/home"
find "$P" -name "__pycache__" -type d -prune -exec rm -rf {} + 2>/dev/null
echo "== $(date '+%F %T.%3N') HYGIENE: sibling_cache emptied, bytecode purged" >> "$LOG"
SRC_START=$P/logs/sources_at_start.txt
find "$P" -type f -not -path '*/logs/*' -not -path '*/__pycache__/*' \
  -not -path '*/sibling_cache/*' -not -path '*/reports/*' -not -name 'PACKAGE_MANIFEST.tsv' \
  | sort | xargs -d '\n' sha256sum > "$SRC_START"
echo "== $(date '+%F %T.%3N') DECISION INPUTS FROZEN: $(wc -l < "$SRC_START") files" >> "$LOG"

# THE RED-TO-GREEN CONTROLS OF THIS ROUND BELONG IN THE FOCUSED STEP, including the
# fail-closed refusals. They were only reached by the full suite at step 8, which is
# not the order the task specifies.
step "1 restore the replacement ledger from the exact surviving bytes, by identity" $PY restore_ledger.py
step "2 exact attempt/evidence accounting against its binding (owners decide parse and shape)" $PY proofs/accepted_evidence_census.py
step "3 focused controls, every test file (output-readers by marker later)" \
  $PY -m pytest tests/test_*.py -m "not reads_chain_outputs" \
      -q -p no:cacheprovider --basetemp=/home/faisal/.core827_backups/recovery_1531/pt_suite \
      --import-mode=importlib
step "4 verify the accepted-checkpoint inventory" $PY verify_accepted_checkpoints.py
step "4b verify the fixed decision inputs (transcript prefix, git store, mounts, resume inputs)" $PY verify_fixed_inputs.py
step "5 verify the signer handoff" $PY verify_signer_handoff.py
# RECEIPT RECONSTRUCTION is a deterministic prerequisite, not finalization
step "6 A3 primary receipt reconstructed from surviving evidence, no call" $PY build_a3_receipt.py
step "6b A3 retry receipt reconstructed from surviving evidence, no call" $PY build_a3_retry_receipt.py
# THE PROJECTION TABLE from the freeze's own walk: what may appear at the historical path
step "7 package-backed projection table from the freeze's own walk" $PY project_historical_tree.py build
# THE ACTUAL FINALIZATION, BOUNDARY AND ENTRY POINT at the historical path, inside a
# private mount namespace whose /tmp is a tmpfs projected from manifested bytes only
step "8 isolated: a1_finalize primary and retry, pinned a3_evidence boundary, real __main__" ./build_a3_finalization.sh prove
step "9 every case mutation" $PY mutations.py
step "9b regenerated inventory" $PY branch_inventory.py
step "9c exhaustive exact-credit audit" $PY proofs/exhaustive_audit.py
step "10 purge generated bytecode" find . -name "__pycache__" -type d -prune -exec rm -rf {} +

# THE FREEZE COMES BEFORE THE SUITE. Every package-content report is final by now
# (steps 2 and 3 wrote the last of them; the audit writes only into logs/, which the
# manifest skips). The suite CONTAINS the self-verifying-manifest test, so running it
# against a manifest frozen before this round's new files fails for a reason that has
# nothing to do with the package. Frozen ONCE here, verified at the end without being
# rewritten.
step "11 freeze once, all package-content reports final" $PY freeze_package.py
step "12 full affected suite" \
  $PY -m pytest tests -q -p no:cacheprovider \
      --basetemp=/home/faisal/.core827_backups/recovery_1531/pt_suite \
      --import-mode=importlib
step "13 package verification, no rewrite" $PY freeze_package.py --verify

SRC_END=$P/logs/sources_at_end.txt
find "$P" -type f -not -path '*/logs/*' -not -path '*/__pycache__/*' \
  -not -path '*/sibling_cache/*' -not -path '*/reports/*' -not -name 'PACKAGE_MANIFEST.tsv' \
  | sort | xargs -d '\n' sha256sum > "$SRC_END"
if ! diff -q "$SRC_START" "$SRC_END" > /dev/null; then
  echo "!! SOURCES CHANGED DURING THE RUN - the evidence is void" >> "$LOG"
  diff "$SRC_START" "$SRC_END" >> "$LOG"
  exit 1
fi
echo "== $(date '+%F %T.%3N') DECISION INPUTS UNCHANGED THROUGHOUT: $(wc -l < "$SRC_END") files" >> "$LOG"
echo "ORDERED RUN COMPLETE" >> "$LOG"
# THE COMPLETED LOG IS PINNED SEPARATELY (Codex SEQ 1559 item 5): logs/ are outside the
# manifest, so the log's own digest, taken after its final line, is the pin the report
# quotes; nothing appended later can hide behind the manifest.
sha256sum "$LOG" | awk '{print $1}' > "${LOG%.txt}.sha256"
