#!/bin/bash
# ONE sequential evidence run (Codex SEQ 1556 item 4). The previous round started the
# audit and the suite seven seconds apart, so they overlapped: concurrent tests are not
# proof of isolated state. Each step here waits for the one before it, and every step
# is stamped so the ORDER is part of the evidence, not a claim about it.
set -u
P=/home/faisal/.core827_backups/recovery_1531/regen_1541
# -u: WITHOUT IT A KILLED STEP LEAVES NO OUTPUT AT ALL. Buffered stdout dies with
# the process, which is exactly what made an earlier silent death hard to trace.
PY="/home/faisal/EventMarketDB/venv/bin/python -u"
export PYTHONDONTWRITEBYTECODE=1
LOG=$P/logs/ordered_1560.txt
: > "$LOG"
step() {
  echo "== $(date '+%F %T.%3N') BEGIN $1" >> "$LOG"
  shift
  "$@" >> "$LOG" 2>&1
  # CAPTURE rc FIRST. Writing `rc=$?` inside an echo whose argument also contains
  # $(date ...) reports the DATE's status: the command substitution runs before the
  # expansion of $?, so every step logged rc=0 - including one the kernel killed.
  rc=$?
  echo "== $(date '+%F %T.%3N') END   rc=$rc" >> "$LOG"
  if [ "$rc" -ne 0 ]; then
    echo "!! STEP FAILED rc=$rc - the ordered run stops here" >> "$LOG"
    exit "$rc"
  fi
}
cd "$P" || exit 1

# PROVE THE RUN IS FROZEN. The previous chain began at 16:41:47 and I then edited a
# proof at 16:48:55 and added a test at 16:55:32, so its early steps did not cover the
# sources its later steps used. Every source and test is hashed HERE and re-hashed at
# the end; any difference voids the run rather than being found by a reviewer.
# FRESH, ISOLATED, EMPTY CACHE and no bytecode before anything is frozen or run: a
# cache built against other inputs must never be served (Codex SEQ 1559 item 2).
rm -rf "$P/sibling_cache" && mkdir -p "$P/sibling_cache"
# the resume run's HOME is the package's own `home/`: empty before the run, so any file
# a process writes there shows in the decision-input diff rather than surviving unseen
rm -rf "$P/home" && mkdir -p "$P/home"
find "$P" -name "__pycache__" -type d -prune -exec rm -rf {} + 2>/dev/null
echo "== $(date '+%F %T.%3N') HYGIENE: sibling_cache emptied, bytecode purged" >> "$LOG"
SRC_START=$P/logs/sources_at_start.txt
find "$P" -type f -not -path '*/logs/*' -not -path '*/__pycache__/*' \
  -not -path '*/sibling_cache/*' -not -path '*/reports/*' -not -name 'PACKAGE_MANIFEST.tsv' \
  | sort | xargs -d '\n' sha256sum > "$SRC_START"
echo "== $(date '+%F %T.%3N') DECISION INPUTS FROZEN: $(wc -l < "$SRC_START") files" >> "$LOG"

# THE RED-TO-GREEN CONTROLS OF THIS ROUND BELONG IN THE FOCUSED STEP, including the
# fail-closed refusals. They were only reached by the full suite at step 8, which is
# not the order the task specifies.
step "1 focused RED-to-green controls, every test file (output-readers by marker later)" \
  $PY -m pytest tests/test_*.py -m "not reads_chain_outputs" \
      -q -p no:cacheprovider --basetemp=/home/faisal/.core827_backups/recovery_1531/pt_suite \
      --import-mode=importlib
# THE PACKAGE AUTHORITIES ARE VERIFIED INSIDE THE CHAIN, not by hand. Both verifiers
# decide whether the accepted checkpoints and the signer handoff still hold; a decision
# that only ever ran outside the proof is not part of the proof.
step "2 verify the accepted-checkpoint inventory" $PY verify_accepted_checkpoints.py
step "2b verify the fixed decision inputs (transcript prefix, git store, resume inputs)" $PY verify_fixed_inputs.py
step "3 verify the signer handoff" $PY verify_signer_handoff.py
step "3b the real no-model resume path, to completion, inside the package" $PY run_resume_path.py
step "4 every case mutation" $PY mutations.py
step "5 regenerated inventory" $PY branch_inventory.py
step "6 exhaustive exact-credit audit" $PY proofs/exhaustive_audit.py
# THE CENSUS IS PART OF THE PROOF, not a side errand run by hand. Its report is
# package content, so a stale file from an earlier run must never reach the freeze.
step "7 full open census at the replay boundary" $PY proofs/open_population.py
# GENERATED BYTECODE IS NOT PACKAGE CONTENT. Five .pyc were present in the last
# freeze despite my claiming their removal; purge immediately before freezing so
# nothing written by the steps above can survive into the manifest.
step "8 purge generated bytecode" find . -name "__pycache__" -type d -prune -exec rm -rf {} +

# THE FREEZE COMES BEFORE THE SUITE. Every package-content report is final by now
# (steps 2 and 3 wrote the last of them; the audit writes only into logs/, which the
# manifest skips). The suite CONTAINS the self-verifying-manifest test, so running it
# against a manifest frozen before this round's new files fails for a reason that has
# nothing to do with the package. Frozen ONCE here, verified at the end without being
# rewritten.
step "9 freeze once, all package-content reports final" $PY freeze_package.py
step "10 full affected suite" \
  $PY -m pytest tests -q -p no:cacheprovider \
      --basetemp=/home/faisal/.core827_backups/recovery_1531/pt_suite \
      --import-mode=importlib
step "11 package verification, no rewrite" $PY freeze_package.py --verify

SRC_END=$P/logs/sources_at_end.txt
find "$P" -type f -not -path '*/logs/*' -not -path '*/__pycache__/*' \
  -not -path '*/sibling_cache/*' -not -path '*/reports/*' -not -name 'PACKAGE_MANIFEST.tsv' \
  | sort | xargs -d '\n' sha256sum > "$SRC_END"
if ! diff -q "$SRC_START" "$SRC_END" > /dev/null; then
  echo "!! SOURCES CHANGED DURING THE RUN - the evidence is void" >> "$LOG"
  diff "$SRC_START" "$SRC_END" >> "$LOG"
  exit 1
fi
echo "== $(date '+%F %T.%3N') DECISION INPUTS UNCHANGED THROUGHOUT: $(wc -l < "$SRC_END") files" >> "$LOG"
echo "ORDERED RUN COMPLETE" >> "$LOG"
# THE COMPLETED LOG IS PINNED SEPARATELY (Codex SEQ 1559 item 5): logs/ are outside the
# manifest, so the log's own digest, taken after its final line, is the pin the report
# quotes; nothing appended later can hide behind the manifest.
sha256sum "$LOG" | awk '{print $1}' > "${LOG%.txt}.sha256"
