apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-05-15T09:19:09Z"
    name: local-path
    resourceVersion: "1013"
    uid: 66c2109c-30a7-4aab-a12c-130cbed60b5c
  provisioner: rancher.io/local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
- allowedTopologies:
  - matchLabelExpressions:
    - key: kubernetes.io/hostname
      values:
      - minisforum3
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"allowedTopologies":[{"matchLabelExpressions":[{"key":"kubernetes.io/hostname","values":["minisforum3"]}]}],"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path-minisforum3"},"parameters":{"path":"/opt/local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Retain","volumeBindingMode":"WaitForFirstConsumer"}
    creationTimestamp: "2025-07-03T10:37:38Z"
    name: local-path-minisforum3
    resourceVersion: "5147423"
    uid: cedf7dc9-769e-43d6-8583-4cdee9b9db00
  parameters:
    path: /opt/local-path
  provisioner: rancher.io/local-path
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
kind: List
metadata:
  resourceVersion: ""
