name: .env Safety Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-dotenv-safety:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Make safety check executable
      run: chmod +x scripts/check-dotenv-safety.sh
    
    - name: Run .env safety check
      run: ./scripts/check-dotenv-safety.sh
      
    - name: Check for new .env files
      run: |
        if find . -name ".env*" -type f ! -path "./venv/*" ! -path "./.git/*" | grep -v ".env.example"; then
          echo "❌ Found .env files that should not be committed"
          exit 1
        fi